import enum
from datetime import datetime

from sqlalchemy import String, DateTime, Enum, Boolean, ForeignKey, Float
from sqlalchemy.orm import Mapped, mapped_column, relationship

from db.session import Base


class AlertType(str, enum.Enum):
    OVERDUE = "overdue"
    EXPIRING_SOON = "expiring_soon"
    ANOMALY = "anomaly"
    MAINTENANCE_DUE = "maintenance_due"
    UNASSIGNED_IDLE = "unassigned_idle"


class AlertSeverity(str, enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class Alert(Base):
    """
    Generated by RentalService / AnomalyDetector / scheduler jobs.
    This table is the single feed for the dashboard's Alerts Center.
    """
    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    equipment_id: Mapped[str] = mapped_column(ForeignKey("equipment.equipment_id"), index=True)
    type: Mapped[AlertType] = mapped_column(Enum(AlertType), index=True)
    severity: Mapped[AlertSeverity] = mapped_column(Enum(AlertSeverity), default=AlertSeverity.MEDIUM)
    message: Mapped[str] = mapped_column(String(255))
    confidence: Mapped[float | None] = mapped_column(Float, nullable=True)  # for ML-driven alerts

    resolved: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    equipment = relationship("Equipment", back_populates="alerts")
